services:
  chatbot:
    build: .
    container_name: bot-whatsapp
    ports:
      - "8000:8000" 
    volumes:
      - .:/app     
    restart: always
    env_file:
      - .env
  chatbot_frontend:
    build: ./frontend
    container_name: bot-whatsapp-frontend
    ports:
      - "8001:5173" 
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules   
    restart: always