# ==============================================================================
# FILE: app/dtos/dtos.py
# DESCRIPTION: Pydantic models for data validation and transfer.
# ==============================================================================

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, Any, Dict

class AIAnalysisDTO(BaseModel):
    """
    Data Transfer Object for structured AI analysis results.
    Ensures the LLM response contains all necessary fields.
    """
    model_config = ConfigDict(frozen=True)

    detected_language: str = Field(..., description="ISO language code detected by the AI")
    intent: str = Field(..., description="The classified intent of the user message")
    field_value: Optional[str] = Field(None, description="Extracted entity value like NIF or Address")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="AI confidence in the classification")
    response_draft: str = Field(..., description="Suggested response generated by the AI")

class IncomingMessageDTO(BaseModel):
    """
    Data Transfer Object representing a validated incoming WhatsApp message.
    """
    model_config = ConfigDict(frozen=True)

    wa_id: str = Field(..., description="WhatsApp ID of the sender")
    sender_name: str = Field(..., description="Full name of the sender")
    message_body: str = Field(..., description="Content of the message sent")

    @property
    def first_name(self) -> str:
        """Extracts the first name from the full sender name."""
        return self.sender_name.split()[0] if self.sender_name else ""
    
class ServiceRequestDTO(BaseModel):
    """
    Data Transfer Object for displaying service requests in the dashboard.
    Standardizes the output for the Frontend.
    """
    model_config = ConfigDict(frozen=True)

    id: int = Field(..., description="Unique database ID of the request")
    customer: str = Field(..., description="Full name of the customer")
    wa_id: str = Field(..., description="WhatsApp phone number ID")
    intent: str = Field(..., description="Classified intent (e.g., alterar_nif)")
    field_value: Optional[str] = Field(None, description="Extracted value like NIF number")
    user_input: Optional[str] = Field(None, description="The original text sent by the user")
    response_text: str = Field(..., description="The response generated or approved for the user")
    date: str = Field(..., description="Formatted creation date (YYYY-MM-DD HH:MM)")
    system_simulation: Optional[Dict[str, Any]] = Field(
        default={}, 
        description="Data generated by the Command simulation logic"
    )